# Generated by Django 6.0.5 on 2026-05-28 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='color',
            field=models.CharField(default='primary', max_length=20),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='fecha_limite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='prioridad',
            field=models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=10),
        ),
    ]
