# Generated by Django 6.0.5 on 2026-05-29 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_tarjeta_color_tarjeta_fecha_limite_tarjeta_prioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='completada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='etiqueta',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
