# Generated by Django 6.0.7 on 2026-07-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_tarjeta_completada_tarjeta_etiqueta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='color',
            field=models.CharField(choices=[('primary', 'Azul'), ('success', 'Verde'), ('danger', 'Rojo'), ('warning', 'Amarillo'), ('dark', 'Negro'), ('info', 'Celeste')], default='primary', max_length=20),
        ),
    ]
