# Generated by Django 6.0.7 on 2026-07-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_alter_tarjeta_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lista',
            options={'ordering': ['orden']},
        ),
        migrations.AlterModelOptions(
            name='tarjeta',
            options={'ordering': ['orden']},
        ),
        migrations.AddField(
            model_name='lista',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
